package com.romankozak.forwardappmobile.data.hierarchy

import com.romankozak.forwardappmobile.shared.core.domain.hierarchy.HierarchyTargetRef
import com.romankozak.forwardappmobile.shared.core.domain.hierarchy.HierarchyTargetType
import com.romankozak.forwardappmobile.shared.core.domain.hierarchy.PlacementId
import com.romankozak.forwardappmobile.shared.core.domain.hierarchy.PlacementKind

sealed interface HierarchyStructuralOperand {
    data class MoveOccurrence(
        val placementId: PlacementId,
        val newParentPlacementId: PlacementId?,
    ) : HierarchyStructuralOperand

    data class RemoveOccurrence(
        val placementId: PlacementId,
    ) : HierarchyStructuralOperand

    data class CreateAppearance(
        val target: HierarchyTargetRef,
        val parentPlacementId: PlacementId?,
        val placementKind: PlacementKind,
    ) : HierarchyStructuralOperand

    /**
     * Structural half of a shallow target clone. sourceOccurrenceId correlates
     * this operand with CloneWorkspaceShallow without pretending the future
     * cloned target id already exists at planning time.
     */
    data class CreatePrimaryForClonedWorkspace(
        val sourceOccurrenceId: PlacementId,
        val parentPlacementId: PlacementId?,
    ) : HierarchyStructuralOperand
}

/**
 * Occurrence-scoped synthetic Group/NoGroup mutation.
 *
 * These operands are deliberately separate from H1 topology. A future P2
 * executor must apply them atomically with their structural sibling operands.
 */
sealed interface HierarchyOccurrenceScopeOperand {
    data class SetRootGroupScope(
        val placementId: PlacementId,
        val groupSubjectId: String?,
    ) : HierarchyOccurrenceScopeOperand

    /**
     * Creates a fresh LINK root occurrence and its Group scope in one fused
     * operation. sourceOccurrenceId is correlation/provenance only; the new
     * durable PlacementId is generated by the executor.
     */
    data class CreateRootLinkAppearance(
        val sourceOccurrenceId: PlacementId,
        val target: HierarchyTargetRef,
        val groupSubjectId: String,
    ) : HierarchyOccurrenceScopeOperand

    data class RetireRootGroupScope(
        val placementId: PlacementId,
    ) : HierarchyOccurrenceScopeOperand
}

sealed interface HierarchySemanticOperand {
    data class EnsureDirectionFrontLinkIfEnabled(
        val parentWorkspaceTarget: HierarchyTargetRef,
        val childWorkspaceTarget: HierarchyTargetRef,
    ) : HierarchySemanticOperand

    /**
     * Canonical V2 semantic projection: live PART_OF for this ManagedSubject
     * must equal the distinct non-null Group subjects represented by its live
     * root occurrence scopes.
     */
    data class ReconcileBeaconGroupMembershipFromRootScopes(
        val target: HierarchyTargetRef,
    ) : HierarchySemanticOperand
}

sealed interface HierarchyOperationalOperand {
    data class AddBeaconOwnerAssociation(
        val ownerTarget: HierarchyTargetRef,
        val legacyBeaconId: String,
    ) : HierarchyOperationalOperand

    data class ReplaceBeaconOwnerAssociation(
        val ownerTarget: HierarchyTargetRef,
        val legacyBeaconId: String,
    ) : HierarchyOperationalOperand

    data class ClearBeaconOwnerAssociations(
        val ownerTarget: HierarchyTargetRef,
    ) : HierarchyOperationalOperand
}

sealed interface HierarchyTargetOperand {
    data class CloneWorkspaceShallow(
        val sourceOccurrenceId: PlacementId,
        val sourceTarget: HierarchyTargetRef,
    ) : HierarchyTargetOperand

    data class CloneBeaconTarget(
        val sourceTarget: HierarchyTargetRef,
        val legacyBeaconId: String,
    ) : HierarchyTargetOperand

    data class DeleteTarget(
        val target: HierarchyTargetRef,
    ) : HierarchyTargetOperand

    data class DeleteStandaloneWorkspaceTargetSubtree(
        val rootTarget: HierarchyTargetRef,
    ) : HierarchyTargetOperand
}

data class HierarchyActionPlan(
    val structural: List<HierarchyStructuralOperand> = emptyList(),
    val occurrenceScope: List<HierarchyOccurrenceScopeOperand> = emptyList(),
    val semantic: List<HierarchySemanticOperand> = emptyList(),
    val operational: List<HierarchyOperationalOperand> = emptyList(),
    val target: List<HierarchyTargetOperand> = emptyList(),
)

sealed interface HierarchyActionPlanDecision {
    data class Planned(
        val plan: HierarchyActionPlan,
    ) : HierarchyActionPlanDecision

    data class Unsupported(
        val reason: String,
    ) : HierarchyActionPlanDecision

    data class RequiresProductDecision(
        val reason: String,
    ) : HierarchyActionPlanDecision
}

/**
 * H4/P1 pure mixed-domain semantic planner.
 *
 * It executes nothing and has no production caller. P2 remains the first
 * authority-bearing hierarchy slice.
 */
object HierarchyMixedDomainCommandSemantics {
    /**
     * CURRENT Context semantics:
     *
     * PRIMARY CUT -> move PRIMARY.
     * LINK CUT -> remove selected LINK, then move the target PRIMARY.
     */
    fun planContextCutToParent(
        selected: HierarchyClipboardOccurrence,
        primaryOccurrence: HierarchyOccurrenceRef,
        destinationParentPlacementId: PlacementId?,
        destinationParentTarget: HierarchyTargetRef?,
    ): HierarchyActionPlan {
        requireContextWorkspaceSource(selected)
        requireSameTarget(selected.occurrence, primaryOccurrence)
        require(primaryOccurrence.placementKind == PlacementKind.PRIMARY)

        val structural =
            buildList {
                if (
                    selected.occurrence.placementKind == PlacementKind.LINK &&
                    selected.occurrence.parentPlacementId != destinationParentPlacementId
                ) {
                    add(
                        HierarchyStructuralOperand.RemoveOccurrence(
                            selected.occurrence.placementId,
                        ),
                    )
                }
                if (primaryOccurrence.parentPlacementId != destinationParentPlacementId) {
                    add(
                        HierarchyStructuralOperand.MoveOccurrence(
                            placementId = primaryOccurrence.placementId,
                            newParentPlacementId = destinationParentPlacementId,
                        ),
                    )
                }
            }

        val semantic =
            if (
                primaryOccurrence.parentPlacementId != destinationParentPlacementId &&
                destinationParentTarget != null
            ) {
                listOf(
                    HierarchySemanticOperand.EnsureDirectionFrontLinkIfEnabled(
                        parentWorkspaceTarget = destinationParentTarget,
                        childWorkspaceTarget = selected.occurrence.target,
                    ),
                )
            } else {
                emptyList()
            }

        return HierarchyActionPlan(
            structural = structural,
            semantic = semantic,
        )
    }

    fun planWorkspaceCutToParent(
        selected: HierarchyClipboardOccurrence,
        destinationParentPlacementId: PlacementId?,
    ): HierarchyActionPlan {
        require(selected.sourceKind == HierarchyClipboardSourceKind.WORKSPACE)
        requireWorkspaceTarget(selected.occurrence.target)

        return HierarchyActionPlan(
            structural =
                listOf(
                    HierarchyStructuralOperand.MoveOccurrence(
                        placementId = selected.occurrence.placementId,
                        newParentPlacementId = destinationParentPlacementId,
                    ),
                ),
        )
    }

    /**
     * Concrete Workspace parent paste.
     *
     * CURRENT Workspace clipboard supports COPY/CUT, not LINK.
     * COPY is shallow target clone + new PRIMARY occurrence.
     * CUT moves the exact selected Workspace occurrence.
     */
    fun planWorkspacePasteIntoParent(
        intent: HierarchyClipboardIntent,
    ): HierarchyActionPlanDecision {
        val destination =
            intent.destination as? HierarchyClipboardDestination.ParentOccurrence
                ?: return HierarchyActionPlanDecision.Unsupported(
                    "Workspace paste requires ParentOccurrence destination",
                )
        if (intent.sources.any { it.sourceKind != HierarchyClipboardSourceKind.WORKSPACE }) {
            return HierarchyActionPlanDecision.Unsupported(
                "Workspace parent paste accepts only Workspace sources",
            )
        }
        intent.sources.forEach { requireWorkspaceTarget(it.occurrence.target) }

        return when (intent.operation) {
            HierarchyClipboardOperation.CUT ->
                HierarchyActionPlanDecision.Planned(
                    HierarchyActionPlan(
                        structural =
                            intent.sources.map { source ->
                                HierarchyStructuralOperand.MoveOccurrence(
                                    placementId = source.occurrence.placementId,
                                    newParentPlacementId = destination.parentPlacementId,
                                )
                            },
                    ),
                )

            HierarchyClipboardOperation.COPY ->
                HierarchyActionPlanDecision.Planned(
                    HierarchyActionPlan(
                        structural =
                            intent.sources.map { source ->
                                HierarchyStructuralOperand.CreatePrimaryForClonedWorkspace(
                                    sourceOccurrenceId = source.occurrence.placementId,
                                    parentPlacementId = destination.parentPlacementId,
                                )
                            },
                        target =
                            intent.sources.map { source ->
                                HierarchyTargetOperand.CloneWorkspaceShallow(
                                    sourceOccurrenceId = source.occurrence.placementId,
                                    sourceTarget = source.occurrence.target,
                                )
                            },
                    ),
                )

            HierarchyClipboardOperation.LINK ->
                HierarchyActionPlanDecision.Unsupported(
                    "CURRENT Workspace clipboard has no LINK mode",
                )
        }
    }

    /**
     * Concrete Context compatibility parent paste.
     *
     * COPY is shallow target clone + PRIMARY occurrence.
     * LINK creates only another LINK occurrence.
     * CUT follows CURRENT selected-occurrence semantics through
     * planContextCutToParent and therefore may include Direction companion.
     */
    fun planContextPasteIntoParent(
        intent: HierarchyClipboardIntent,
        primaryOccurrencesByTarget: Map<HierarchyTargetRef, HierarchyOccurrenceRef>,
        destinationParentTarget: HierarchyTargetRef?,
    ): HierarchyActionPlanDecision {
        val destination =
            intent.destination as? HierarchyClipboardDestination.ParentOccurrence
                ?: return HierarchyActionPlanDecision.Unsupported(
                    "Context paste requires ParentOccurrence destination",
                )
        if (intent.sources.any { it.sourceKind != HierarchyClipboardSourceKind.CONTEXT_COMPATIBILITY }) {
            return HierarchyActionPlanDecision.Unsupported(
                "Context parent paste accepts only Context compatibility sources",
            )
        }
        intent.sources.forEach { requireWorkspaceTarget(it.occurrence.target) }

        return when (intent.operation) {
            HierarchyClipboardOperation.COPY ->
                HierarchyActionPlanDecision.Planned(
                    HierarchyActionPlan(
                        structural =
                            intent.sources.map { source ->
                                HierarchyStructuralOperand.CreatePrimaryForClonedWorkspace(
                                    sourceOccurrenceId = source.occurrence.placementId,
                                    parentPlacementId = destination.parentPlacementId,
                                )
                            },
                        target =
                            intent.sources.map { source ->
                                HierarchyTargetOperand.CloneWorkspaceShallow(
                                    sourceOccurrenceId = source.occurrence.placementId,
                                    sourceTarget = source.occurrence.target,
                                )
                            },
                    ),
                )

            HierarchyClipboardOperation.LINK ->
                HierarchyActionPlanDecision.Planned(
                    HierarchyActionPlan(
                        structural =
                            intent.sources.map { source ->
                                HierarchyStructuralOperand.CreateAppearance(
                                    target = source.occurrence.target,
                                    parentPlacementId = destination.parentPlacementId,
                                    placementKind = PlacementKind.LINK,
                                )
                            },
                    ),
                )

            HierarchyClipboardOperation.CUT -> {
                val plans = mutableListOf<HierarchyActionPlan>()
                for (source in intent.sources) {
                    val primary =
                        primaryOccurrencesByTarget[source.occurrence.target]
                            ?: return HierarchyActionPlanDecision.RequiresProductDecision(
                                "Context CUT requires the target PRIMARY occurrence",
                            )
                    plans +=
                        planContextCutToParent(
                            selected = source,
                            primaryOccurrence = primary,
                            destinationParentPlacementId = destination.parentPlacementId,
                            destinationParentTarget = destinationParentTarget,
                        )
                }
                HierarchyActionPlanDecision.Planned(
                    HierarchyActionPlan(
                        structural = plans.flatMap { it.structural },
                        occurrenceScope = plans.flatMap { it.occurrenceScope },
                        semantic = plans.flatMap { it.semantic },
                    ),
                )
            }
        }
    }

    /**
     * CURRENT Workspace paste into Beacon changes only operational ownership.
     *
     * CURRENT Context COPY/LINK also changes only operational ownership.
     * Context CUT additionally detaches its displayed location before replacing
     * the Beacon owner association:
     * - selected LINK is removed;
     * - target PRIMARY is moved to root when it was structurally nested.
     *
     * Beacon itself is not made a structural parent by these CURRENT paths.
     */
    fun planOwnerPasteIntoBeacon(
        intent: HierarchyClipboardIntent,
        primaryOccurrencesByTarget: Map<HierarchyTargetRef, HierarchyOccurrenceRef> = emptyMap(),
    ): HierarchyActionPlanDecision {
        val destination =
            intent.destination as? HierarchyClipboardDestination.BeaconOwner
                ?: return HierarchyActionPlanDecision.Unsupported(
                    "Owner paste requires BeaconOwner destination",
                )

        if (intent.sources.any { it.sourceKind == HierarchyClipboardSourceKind.BEACON }) {
            return HierarchyActionPlanDecision.Unsupported(
                "Beacon source uses Beacon hierarchy semantics",
            )
        }
        if (intent.sources.any { it.occurrence.target.type != HierarchyTargetType.WORKSPACE }) {
            return HierarchyActionPlanDecision.Unsupported(
                "Operational owner source must resolve to WORKSPACE target",
            )
        }

        val structural = mutableListOf<HierarchyStructuralOperand>()

        if (intent.operation == HierarchyClipboardOperation.CUT) {
            for (source in intent.sources) {
                if (source.sourceKind != HierarchyClipboardSourceKind.CONTEXT_COMPATIBILITY) {
                    continue
                }

                val primary =
                    primaryOccurrencesByTarget[source.occurrence.target]
                        ?: return HierarchyActionPlanDecision.RequiresProductDecision(
                            "Context CUT into Beacon requires the target PRIMARY occurrence",
                        )

                requireSameTarget(source.occurrence, primary)
                require(primary.placementKind == PlacementKind.PRIMARY)

                if (source.occurrence.placementKind == PlacementKind.LINK) {
                    structural +=
                        HierarchyStructuralOperand.RemoveOccurrence(
                            source.occurrence.placementId,
                        )
                }

                if (primary.parentPlacementId != null) {
                    structural +=
                        HierarchyStructuralOperand.MoveOccurrence(
                            placementId = primary.placementId,
                            newParentPlacementId = null,
                        )
                }
            }
        }

        val operational =
            intent.sources.map { source ->
                when (intent.operation) {
                    HierarchyClipboardOperation.CUT ->
                        HierarchyOperationalOperand.ReplaceBeaconOwnerAssociation(
                            ownerTarget = source.occurrence.target,
                            legacyBeaconId = destination.legacyBeaconId,
                        )

                    HierarchyClipboardOperation.COPY,
                    HierarchyClipboardOperation.LINK,
                    ->
                        HierarchyOperationalOperand.AddBeaconOwnerAssociation(
                            ownerTarget = source.occurrence.target,
                            legacyBeaconId = destination.legacyBeaconId,
                        )
                }
            }

        return HierarchyActionPlanDecision.Planned(
            HierarchyActionPlan(
                structural = structural,
                operational = operational,
            ),
        )
    }

    /**
     * CURRENT NoBeacon accepts only Context CUT. NoBeacon itself is synthetic:
     * detach the displayed occurrence, move target PRIMARY to root if needed,
     * and independently remove Beacon owner associations.
     */
    fun planPasteIntoNoBeacon(
        intent: HierarchyClipboardIntent,
        primaryOccurrencesByTarget: Map<HierarchyTargetRef, HierarchyOccurrenceRef> = emptyMap(),
    ): HierarchyActionPlanDecision {
        if (intent.destination !is HierarchyClipboardDestination.NoBeacon) {
            return HierarchyActionPlanDecision.Unsupported("Destination is not NoBeacon")
        }
        if (intent.operation != HierarchyClipboardOperation.CUT) {
            return HierarchyActionPlanDecision.Unsupported(
                "CURRENT NoBeacon accepts only Context CUT",
            )
        }
        if (intent.sources.any { it.sourceKind != HierarchyClipboardSourceKind.CONTEXT_COMPATIBILITY }) {
            return HierarchyActionPlanDecision.Unsupported(
                "CURRENT NoBeacon has no Workspace or Beacon paste command",
            )
        }

        val structural = mutableListOf<HierarchyStructuralOperand>()
        for (source in intent.sources) {
            requireWorkspaceTarget(source.occurrence.target)
            val primary =
                primaryOccurrencesByTarget[source.occurrence.target]
                    ?: return HierarchyActionPlanDecision.RequiresProductDecision(
                        "Context CUT into NoBeacon requires target PRIMARY occurrence",
                    )

            requireSameTarget(source.occurrence, primary)
            require(primary.placementKind == PlacementKind.PRIMARY)

            if (source.occurrence.placementKind == PlacementKind.LINK) {
                structural +=
                    HierarchyStructuralOperand.RemoveOccurrence(
                        source.occurrence.placementId,
                    )
            }
            if (primary.parentPlacementId != null) {
                structural +=
                    HierarchyStructuralOperand.MoveOccurrence(
                        placementId = primary.placementId,
                        newParentPlacementId = null,
                    )
            }
        }

        return HierarchyActionPlanDecision.Planned(
            HierarchyActionPlan(
                structural = structural,
                operational =
                    intent.sources.map { source ->
                        HierarchyOperationalOperand.ClearBeaconOwnerAssociations(
                            ownerTarget = source.occurrence.target,
                        )
                    },
            ),
        )
    }

    /**
     * Occurrence-native Beacon Group mutation.
     *
     * CUT moves the exact selected occurrence to root and assigns that exact
     * PlacementId to Group/NoGroup scope. COPY/LINK creates a fresh LINK root
     * occurrence together with its Group scope. Group never becomes an H1
     * parent.
     *
     * PART_OF is reconciled from the complete set of live root scopes for the
     * target, so unrelated same-target Group appearances remain independent.
     */
    fun planBeaconPasteIntoGroup(
        intent: HierarchyClipboardIntent,
    ): HierarchyActionPlanDecision {
        val destination =
            intent.destination as? HierarchyClipboardDestination.Group
                ?: return HierarchyActionPlanDecision.Unsupported(
                    "Beacon Group operation requires Group destination",
                )

        if (intent.sources.any { it.sourceKind != HierarchyClipboardSourceKind.BEACON }) {
            return HierarchyActionPlanDecision.Unsupported(
                "Group membership accepts only Beacon sources",
            )
        }
        if (
            intent.sources.any {
                it.legacySourceId.isNullOrBlank() ||
                    it.occurrence.target.type != HierarchyTargetType.MANAGED_SUBJECT
            }
        ) {
            return HierarchyActionPlanDecision.Unsupported(
                "Beacon source requires legacy id and MANAGED_SUBJECT target",
            )
        }

        return when (intent.operation) {
            HierarchyClipboardOperation.CUT ->
                HierarchyActionPlanDecision.Planned(
                    HierarchyActionPlan(
                        structural =
                            intent.sources.map { source ->
                                HierarchyStructuralOperand.MoveOccurrence(
                                    placementId = source.occurrence.placementId,
                                    newParentPlacementId = null,
                                )
                            },
                        occurrenceScope =
                            intent.sources.map { source ->
                                HierarchyOccurrenceScopeOperand.SetRootGroupScope(
                                    placementId = source.occurrence.placementId,
                                    groupSubjectId = destination.groupSubjectId,
                                )
                            },
                        semantic =
                            intent.sources
                                .map { source -> source.occurrence.target }
                                .distinct()
                                .map { target ->
                                    HierarchySemanticOperand
                                        .ReconcileBeaconGroupMembershipFromRootScopes(target)
                                },
                    ),
                )

            HierarchyClipboardOperation.COPY,
            HierarchyClipboardOperation.LINK,
            -> {
                val groupSubjectId =
                    destination.groupSubjectId
                        ?: return HierarchyActionPlanDecision.Unsupported(
                            "Occurrence-native COPY/LINK cannot create a NoGroup duplicate root",
                        )

                HierarchyActionPlanDecision.Planned(
                    HierarchyActionPlan(
                        occurrenceScope =
                            intent.sources.map { source ->
                                HierarchyOccurrenceScopeOperand.CreateRootLinkAppearance(
                                    sourceOccurrenceId = source.occurrence.placementId,
                                    target = source.occurrence.target,
                                    groupSubjectId = groupSubjectId,
                                )
                            },
                        semantic =
                            intent.sources
                                .map { source -> source.occurrence.target }
                                .distinct()
                                .map { target ->
                                    HierarchySemanticOperand
                                        .ReconcileBeaconGroupMembershipFromRootScopes(target)
                                },
                    ),
                )
            }
        }
    }

    /**
     * Beacon COPY/LINK into Beacon creates an additional structural appearance.
     * Beacon CUT moves the exact selected occurrence under the exact destination
     * occurrence. A selected LINK therefore stays the same LINK occurrence and
     * preserves its PlacementId; the target PRIMARY remains untouched.
     */
    fun planBeaconPasteIntoBeacon(
        intent: HierarchyClipboardIntent,
    ): HierarchyActionPlanDecision {
        val destination =
            intent.destination as? HierarchyClipboardDestination.BeaconOwner
                ?: return HierarchyActionPlanDecision.Unsupported(
                    "Beacon paste requires concrete Beacon occurrence",
                )

        if (intent.sources.any { it.sourceKind != HierarchyClipboardSourceKind.BEACON }) {
            return HierarchyActionPlanDecision.Unsupported(
                "Beacon hierarchy paste accepts only Beacon sources",
            )
        }

        return when (intent.operation) {
            HierarchyClipboardOperation.CUT ->
                HierarchyActionPlanDecision.Planned(
                    HierarchyActionPlan(
                        structural =
                            intent.sources.map { source ->
                                HierarchyStructuralOperand.MoveOccurrence(
                                    placementId = source.occurrence.placementId,
                                    newParentPlacementId = destination.occurrence.placementId,
                                )
                            },
                        occurrenceScope =
                            intent.sources.map { source ->
                                HierarchyOccurrenceScopeOperand.RetireRootGroupScope(
                                    placementId = source.occurrence.placementId,
                                )
                            },
                        semantic =
                            intent.sources
                                .filter {
                                    it.occurrence.target.type ==
                                        HierarchyTargetType.MANAGED_SUBJECT
                                }
                                .map { source -> source.occurrence.target }
                                .distinct()
                                .map { target ->
                                    HierarchySemanticOperand
                                        .ReconcileBeaconGroupMembershipFromRootScopes(target)
                                },
                    ),
                )

            HierarchyClipboardOperation.COPY,
            HierarchyClipboardOperation.LINK,
            ->
                HierarchyActionPlanDecision.Planned(
                    HierarchyActionPlan(
                        structural =
                            intent.sources.map { source ->
                                HierarchyStructuralOperand.CreateAppearance(
                                    target = source.occurrence.target,
                                    parentPlacementId = destination.occurrence.placementId,
                                    placementKind = PlacementKind.LINK,
                                )
                            },
                    ),
                )
        }
    }

    /**
     * True Beacon duplication is a target-clone operation and is deliberately
     * separate from clipboard COPY/LINK, which create additional appearances.
     */
    fun planTrueBeaconDuplicate(
        source: HierarchyClipboardOccurrence,
    ): HierarchyActionPlan {
        require(source.sourceKind == HierarchyClipboardSourceKind.BEACON)
        require(source.occurrence.target.type == HierarchyTargetType.MANAGED_SUBJECT)
        val legacyBeaconId =
            requireNotNull(source.legacySourceId?.takeIf { it.isNotBlank() })

        return HierarchyActionPlan(
            target =
                listOf(
                    HierarchyTargetOperand.CloneBeaconTarget(
                        sourceTarget = source.occurrence.target,
                        legacyBeaconId = legacyBeaconId,
                    ),
                ),
        )
    }

    fun planDestructiveIntent(
        intent: HierarchyDestructiveIntent,
    ): HierarchyActionPlan =
        when (intent) {
            is HierarchyDestructiveIntent.RemoveOccurrence ->
                HierarchyActionPlan(
                    structural =
                        listOf(
                            HierarchyStructuralOperand.RemoveOccurrence(intent.placementId),
                        ),
                )

            is HierarchyDestructiveIntent.DeleteTarget ->
                HierarchyActionPlan(
                    target =
                        listOf(
                            HierarchyTargetOperand.DeleteTarget(intent.target),
                        ),
                )
        }

    fun planStandaloneWorkspaceSubtreeDelete(
        rootTarget: HierarchyTargetRef,
    ): HierarchyActionPlan {
        requireWorkspaceTarget(rootTarget)
        return HierarchyActionPlan(
            target =
                listOf(
                    HierarchyTargetOperand.DeleteStandaloneWorkspaceTargetSubtree(
                        rootTarget,
                    ),
                ),
        )
    }

    private fun requireContextWorkspaceSource(source: HierarchyClipboardOccurrence) {
        require(source.sourceKind == HierarchyClipboardSourceKind.CONTEXT_COMPATIBILITY)
        requireWorkspaceTarget(source.occurrence.target)
    }

    private fun requireWorkspaceTarget(target: HierarchyTargetRef) {
        require(target.type == HierarchyTargetType.WORKSPACE)
    }

    private fun requireSameTarget(
        selected: HierarchyOccurrenceRef,
        primary: HierarchyOccurrenceRef,
    ) {
        require(selected.target == primary.target) {
            "Selected and PRIMARY occurrences must reference the same target"
        }
    }
}
