package com.romankozak.forwardappmobile.sync

import com.romankozak.forwardappmobile.core.data.models.sync.SnapshotBundle

internal fun SnapshotBundle.importItemCount(): Int =
    contexts.size +
        contextParentLinks.size +
        goals.size +
        backlogItems.size +
        backlogOrders.size +
        workspaceDirectionEntries.orEmpty().size +
        workspaceBacklogEntries.orEmpty().size +
        notes.size +
        documents.size +
        musicNotes.size +
        checklists.size +
        checklistItems.size +
        artifacts.size +
        scripts.size +
        attachments.size +
        crossRefs.size +
        inbox.size +
        logs.size +
        canonicalExecutionLogs.orEmpty().size +
        systemApps.size +
        activityRecords.size +
        recentProjectEntries.size +
        linkItemEntities.size +
        dayPlans.size +
        dayFocusItems.size +
        dayTasks.size +
        dayThemeDocuments.size +
        themeDefinitions.orEmpty().size +
        dayThemes.orEmpty().size +
        dayThemeAssignmentDocuments.orEmpty().size +
        dailyMetrics.size +
        conversations.size +
        chatMessages.size +
        conversationFolders.size +
        reminders.size +
        recurringTasks.size +
        tacticalMissions.size +
        tacticalMissionAttachments.size +
        tacticalIterations.size +
        missionStreams.size +
        tacticalActivitySlots.size +
        arcQuests.size +
        aiEvents.size +
        aiInsights.size +
        mainBeacons.size +
        mainBeaconGroups.size +
        mainBeaconGroupMembers.size +
        mainBeaconParentLinks.size +
        mainBeaconContextCrossRefs.size +
        mainBeaconAttachmentCrossRefs.size +
        mainBeaconLevelStatuses.size +
        lifeManagementLevelStatuses.size +
        lifeSystemStates.size +
        contextRoleProfiles.size +
        contextRoleProfileItems.size +
        contextConfigurations.size +
        projectStructureItems.size +
        contextInboxSortingRules.size +
        workspaceProblems.orEmpty().size +
        workspaceProblemWorkspaceRefs.orEmpty().size +
        workspaceProblemAttachmentRefs.orEmpty().size +
        focusContextIntervals.size +
        userStateIntervals.size +
        if (dayManagementRuntimeState != null) 1 else 0
