from __future__ import annotations

from enum import StrEnum


class DayStage(StrEnum):
    NOT_STARTED = "NOT_STARTED"
    PREPARATION = "PREPARATION"
    IMPLEMENTATION = "IMPLEMENTATION"
    FINALIZATION = "FINALIZATION"
    CLOSED = "CLOSED"


class StateClass(StrEnum):
    IDLE = "IDLE"
    ON_TARGET = "ON_TARGET"
    MINOR_USEFUL = "MINOR_USEFUL"
    DRIFT = "DRIFT"
    RECOVERY = "RECOVERY"
    EMERGENCY = "EMERGENCY"


class EventType(StrEnum):
    DAY_STARTED = "DAY_STARTED"
    GOAL_APPROVED = "GOAL_APPROVED"
    MINOR_ACTIVITY_ALLOWED = "MINOR_ACTIVITY_ALLOWED"
    IMPLEMENTATION_STARTED = "IMPLEMENTATION_STARTED"
    TASK_STARTED = "TASK_STARTED"
    CONTROL_CHECK = "CONTROL_CHECK"
    DRIFT_DETECTED = "DRIFT_DETECTED"
    PROTOCOL_OPENED = "PROTOCOL_OPENED"
    DAY_FINALIZATION_STARTED = "DAY_FINALIZATION_STARTED"
    DAY_FINALIZED = "DAY_FINALIZED"
    STATE_RESET = "STATE_RESET"
    AUTO_TRIGGER_FIRED = "AUTO_TRIGGER_FIRED"
    ALARM_RAISED = "ALARM_RAISED"
    ALARMS_ACKED = "ALARMS_ACKED"
