package com.romankozak.forwardappmobile.shared.features.daymanagement.dayplan.domain.model

data class DayTask(
    val id: String,
    val dayPlanId: String,
    val title: String,
    val description: String?,
    val goalId: String?,
    val projectId: String?,
    val activityRecordId: String?,
    val recurringTaskId: String?,
    val taskType: String?,
    val entityId: String?,
    val order: Long,
    val priority: TaskPriority,
    val status: TaskStatus,
    val completed: Boolean,
    val scheduledTime: Long?,
    val estimatedDurationMinutes: Long?,
    val actualDurationMinutes: Long?,
    val dueTime: Long?,
    val valueImportance: Float,
    val valueImpact: Float,
    val effort: Float,
    val cost: Float,
    val risk: Float,
    val location: String?,
    val tags: List<String>?,
    val notes: String?,
    val createdAt: Long,
    val updatedAt: Long?,
    val completedAt: Long?,
    val nextOccurrenceTime: Long?,
    val points: Int,
)
